### ISSUE TITLE
Selfish request

### ISSUE THREAD

**Issue by ralsina** [gwax/www-gwax#1]
I like your theme and would love to see it in themes.getnikola.com :-)

**Comment by gwax** [comment]
Thanks. It has always been my intention to get the theme up on themes.getnikola.com.

In the past, it's been a little bit _too_ custom for public distribution but last time I had some free time, I managed to clean it up a bunch.

I think it probably won't take much work to get it ready to share more publicly at this point. Depending on timing, I may wait until 8.0.0 is released but I might also be able to get it out for 7.x as well.
